version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js...
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -   # Use Node.js 18
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'

